#!/bin/bash

domain=$(sudo yunohost app setting shinken domain)

sudo rm /etc/nginx/conf.d/$domain.d/shinken.conf
sudo rm -rf /home/yunohost.app/shinken

sudo sudo update-rc.d -f shinken remove

sudo service nginx reload
sudo yunohost app ssowatconf